version: '3'
services:
  vibe-atv-game:
    build: .
    ports:
      - "8090:8090"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=8090
    restart: unless-stopped
